-- 즐겨찾기가 가장 많은 식당 정보 출력하기
-- SELECT I.FOOD_TYPE, REST_ID, REST_NAME, I.FAVORITES
-- FROM REST_INFO AS I
-- INNER JOIN (
--      SELECT 
--          FOOD_TYPE,
--          MAX(FAVORITES) AS FAVORITES
--      FROM REST_INFO
--      GROUP BY FOOD_TYPE
--  ) AS F
--  ON I.FOOD_TYPE = F.FOOD_TYPE AND I.FAVORITES = F.FAVORITES
--  ORDER BY I.FOOD_TYPE DESC

SELECT FOOD_TYPE, REST_ID, REST_NAME, FAVORITES
FROM REST_INFO
WHERE FAVORITES IN (
    SELECT MAX(FAVORITES)
    FROM REST_INFO
    GROUP BY FOOD_TYPE
)
GROUP BY FOOD_TYPE
ORDER BY FOOD_TYPE DESC