-- 그룹별 조건에 맞는 식당 목록 출력하기
SELECT MEMBER_NAME, REVIEW_TEXT, DATE_FORMAT(REVIEW_DATE, "%Y-%m-%d") AS REVIEW_DATE
FROM MEMBER_PROFILE AS PROFILE
INNER JOIN (
    SELECT C.MEMBER_ID, REVIEW_TEXT, REVIEW_DATE
    FROM (
        SELECT MEMBER_ID, COUNT(*) AS COUNT
        FROM REST_REVIEW
        GROUP BY MEMBER_ID
        ORDER BY COUNT DESC
        LIMIT 1
    ) AS C
    INNER JOIN REST_REVIEW AS R
    ON C.MEMBER_ID = R.MEMBER_ID
) AS REVIEW
ON PROFILE.MEMBER_ID = REVIEW.MEMBER_ID
ORDER BY REVIEW_DATE, REVIEW_TEXT