-- 식품분류별 가장 비싼 식품의 정보 구하기
SELECT M.CATEGORY, M.MAX_PRICE, P.PRODUCT_NAME
FROM FOOD_PRODUCT AS P
RIGHT JOIN (
    SELECT CATEGORY, MAX(PRICE) AS MAX_PRICE
    FROM FOOD_PRODUCT
    WHERE CATEGORY IN ('과자', '국', '김치', '식용유')
    GROUP BY CATEGORY
) AS M
ON M.MAX_PRICE = P.PRICE AND M.CATEGORY = P.CATEGORY
ORDER BY M.MAX_PRICE DESC