-- 상품을 구매한 회원 비율 구하기
WITH total_num_members_2021 AS (
    SELECT COUNT(*) AS COUNT
    FROM USER_INFO
    WHERE JOINED LIKE '2021%'
)

SELECT 
    YEAR(SALES_DATE) AS YEAR,
    MONTH(SALES_DATE) AS MONTH,
    COUNT(DISTINCT(USER_ID)) AS PURCHASED_USERS,
    ROUND(COUNT(DISTINCT(USER_ID))/COUNT, 1) AS PURCHASED_RATIO
FROM ONLINE_SALE, total_num_members_2021
WHERE USER_ID IN (
    SELECT USER_ID
    FROM USER_INFO
    WHERE JOINED LIKE '2021%'
)
GROUP BY YEAR(SALES_DATE), MONTH(SALES_DATE)
ORDER BY YEAR ASC, MONTH ASC