-- 년, 월, 성별 별 상품 구매 회원 수 구하기
SELECT YEAR(S.SALES_DATE) AS YEAR, MONTH(S.SALES_DATE) AS MONTH, U.GENDER, COUNT(DISTINCT(S.USER_ID)) AS USERS
FROM ONLINE_SALE AS S
INNER JOIN USER_INFO AS U
ON S.USER_ID = U.USER_ID
WHERE GENDER IS NOT NULL
GROUP BY YEAR, MONTH, GENDER
ORDER BY YEAR, MONTH, GENDER