-- 취소되지 않은 진료 예약 조회하기
SELECT APNT_NO, PT_NAME, A.PT_NO, A.MCDP_CD, DR_NAME, APNT_YMD
FROM APPOINTMENT AS A
INNER JOIN DOCTOR AS D ON D.DR_ID = A.MDDR_ID
INNER JOIN PATIENT AS P ON P.PT_NO = A.PT_NO
WHERE A.MCDP_CD = 'CS' AND APNT_CNCL_YN = 'N' AND APNT_YMD LIKE '2022-04-13%'