-- 저자 별 카테고리 별 매출액 집계하기
SELECT AUTHOR_ID, AUTHOR_NAME, CATEGORY, SUM(PRICE * SALES)
FROM BOOK_SALES AS S
LEFT JOIN (
    SELECT BOOK_ID, CATEGORY, B.AUTHOR_ID, PRICE, AUTHOR_NAME
    FROM BOOK AS B
    INNER JOIN AUTHOR AS A 
    ON B.AUTHOR_ID = A.AUTHOR_ID
    # BOOK-AUTHOR INFO TABLE
) AS INFO
ON S.BOOK_ID = INFO.BOOK_ID
WHERE MONTH(SALES_DATE) = '1'
GROUP BY AUTHOR_ID, CATEGORY
ORDER BY AUTHOR_ID, CATEGORY DESC