-- 입양 시간 구하기 (2)
SELECT H.HOUR, COALESCE(COUNT, 0) AS COUNT
FROM (
    SELECT HOUR(DATETIME) AS HOUR, COUNT(*) AS COUNT
    FROM ANIMAL_OUTS
    GROUP BY HOUR
) AS C
RIGHT JOIN (
    WITH RECURSIVE CTE AS (
    SELECT 0 AS HOUR
    UNION ALL
    SELECT HOUR + 1 FROM CTE
    WHERE HOUR < 23
    )
    SELECT HOUR FROM CTE
) AS H
ON H.HOUR = C.HOUR
ORDER BY H.HOUR